main:
  push:
    - stageOne:
      runner:
        cpus: 8
      services:
        - docker
        - git-clone-yyds
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/eryajf/build-env/-/blob/main/env.yaml
          settings:
            force: true
            branch: main
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            target_url: https://github.com/eryajf/rpmbuild.git
            git_email: 'github-actions[bot]@users.noreply.github.com'